version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-container
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: sampletest
